[package]
name = "debug_geordon"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
serde_json = "0.8"
glium = "0.15.0"
glowygraph = "0.7.2"
itertools = "0.5.5"
rnet = {git = "https://github.com/jjgz/rnet"}
